 
[[redirects]]
  from = "/blog*"
  to = "https://netlifyfreeaccount.superblog.cloud/:splat"
  status = 200

[[redirects]]
  from = "/_elderjs/*"
  to = "https://netlifyfreeaccount.superblog.cloud/_elderjs/:splat"
  status = 200 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
